# Generated by Django 4.1.3 on 2022-12-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='total_calories',
            field=models.DecimalField(decimal_places=4, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_carbohydrates',
            field=models.DecimalField(decimal_places=4, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_fats',
            field=models.DecimalField(decimal_places=4, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_proteins',
            field=models.DecimalField(decimal_places=4, max_digits=500),
        ),
    ]
