# Generated by Django 4.1.3 on 2022-12-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_calculator_total_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='user',
        ),
    ]
