# Generated by Django 4.1.3 on 2022-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
