# Generated by Django 4.1.3 on 2022-12-04 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_calculator_product_calculator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='user',
        ),
        migrations.AddField(
            model_name='calculator',
            name='product',
            field=models.ManyToManyField(to='products.products'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
