# Generated by Django 4.1.3 on 2022-12-04 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_remove_calculator_product_remove_calculator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='user',
            field=models.ManyToManyField(related_name='user_calculation', to=settings.AUTH_USER_MODEL),
        ),
    ]
