# Generated by Django 4.1.3 on 2022-12-15 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_calculator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_fats',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='total_proteins',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
    ]
